---
- name: Run preflight checks
  ansible.builtin.import_tasks: preflight.yml

- name: Install prereqs
  become: true
  ansible.builtin.import_tasks: prereqs.yml

- name: Create tmp directory on dest
  become: true
  ansible.builtin.file:
    path: "{{ stagesync_dest_tmp_dir }}"
    owner: "root"
    group: "root"
    mode: "0777"
    state: directory
